version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: ${TZ:-Asia/Ho_Chi_Minh}
      VIRTUAL_HOST: youtube.manhtran.top
      LETSENCRYPT_HOST: youtube.manhtran.top
      VIRTUAL_PORT: 80
